---

- name: Ensure backup dir
  ansible.builtin.file:
    path:  "{{ keycloak_backup_path }}"
    state: directory
    owner: root
    group: root
    mode:  o-rx

- name: Ensure backup script
  ansible.builtin.template:
    src: templates/ansible_keycloak_backup.sh.j2
    dest: "{{ keycloak_backup_script }}"
    owner: root
    group: root
    mode:  u+x,o-r

- name: Ensure restore script
  ansible.builtin.template:
    src: templates/ansible_keycloak_restore.sh.j2
    dest: "{{ keycloak_restore_script }}"
    owner: root
    group: root
    mode:  u+x,o-r

- name: Ensure scheduled backup 
  ansible.builtin.cron:
    cron_file: "ansible_keycloak_backup"
    user:      root
    name:      "ansible keycloak backup"
    job:       "{{ keycloak_backup_script }}"
    hour:      "{{ keycloak_backup_cron_hour }}"
    minute:    "{{ keycloak_backup_cron_minute }}"

...